# Generated by Django 5.2.6 on 2025-09-14 19:31

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RentalObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "minimum_rental_duration",
                    models.DurationField(
                        validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=600))],
                        verbose_name="Минимальное время аренды",
                    ),
                ),
                (
                    "type_obj",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("equipment", "Equipment"),
                            ("kite", "Kite"),
                            ("moto", "Bike"),
                            ("Spa", "Spa"),
                            ("property", "Property"),
                            ("wakeBoard", "Wake Board"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип объекта",
                    ),
                ),
                ("additional_terms", models.TextField(blank=True, null=True, verbose_name="Дополнительные условия")),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Цена за день",
                    ),
                ),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен для аренды")),
            ],
            options={
                "verbose_name": "Объект аренды",
                "verbose_name_plural": "Объекты аренды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название места")),
                ("description", models.TextField(blank=True, verbose_name="Описание места")),
                ("city", models.CharField(blank=True, max_length=255, verbose_name="Город")),
                ("rest_of_address", models.CharField(blank=True, max_length=512, verbose_name="Улица, дом, квартира")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Широта")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Долгота")),
                ("capacity", models.PositiveIntegerField(default=1, verbose_name="Вместимость")),
            ],
            options={
                "verbose_name": "Место оказания услуги",
                "verbose_name_plural": "Места оказания услуг",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="\n            Unique identifier for this user or bot.\n            This number may have more than 32 significant bits and some programming\n            languages may have difficulty/silent defects in interpreting it.\n            But it has at most 52 significant bits, so a 64-bit integer or double-precision\n            float type are safe for storing this identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_bot", models.BooleanField(help_text="True, if this user is a bot")),
                ("first_name", models.CharField(help_text="User's or bot's first name", max_length=64)),
                ("last_name", models.CharField(blank=True, help_text="Optional. User's or bot's last name", max_length=64, null=True)),
                ("username", models.CharField(blank=True, help_text="Optional. User's or bot's username", max_length=32, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, help_text="Optional. IETF language tag of the user's language", max_length=15, null=True),
                ),
                (
                    "is_premium",
                    models.BooleanField(blank=True, help_text="Optional. True, if this user is a Telegram Premium user", null=True),
                ),
                (
                    "added_to_attachment_menu",
                    models.BooleanField(
                        blank=True, help_text="Optional. True, if this user added the bot to the attachment menu", null=True
                    ),
                ),
                (
                    "can_join_groups",
                    models.BooleanField(
                        blank=True, help_text="Optional. True, if the bot can be invited to groups. Returned only in getMe.", null=True
                    ),
                ),
                (
                    "can_read_all_group_messages",
                    models.BooleanField(
                        blank=True, help_text="Optional. True, if privacy mode is disabled for the bot. Returned only in getMe.", null=True
                    ),
                ),
                (
                    "supports_inline_queries",
                    models.BooleanField(
                        blank=True, help_text="Optional. True, if the bot supports inline queries. Returned only in getMe.", null=True
                    ),
                ),
                (
                    "can_connect_to_business",
                    models.BooleanField(
                        blank=True,
                        help_text="Optional. True, if the bot can be connected to a Telegram Business\n            account to receive its messages.\n            Returned only in getMe.",
                        null=True,
                    ),
                ),
                (
                    "has_main_web_app",
                    models.BooleanField(
                        blank=True, help_text="Optional. True, if the bot has a main Web App. Returned only in getMe.", null=True
                    ),
                ),
                ("datetime_joined", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RentalObjectImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to="rental_objects/%Y/%m/%d/",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
                        verbose_name="Изображение",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки")),
                (
                    "rental_object",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="bot_admin.rentalobject"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rentalobject",
            name="current_location",
            field=models.ManyToManyField(
                blank=True, related_name="current_location", to="bot_admin.servicelocation", verbose_name="Где находится"
            ),
        ),
        migrations.CreateModel(
            name="RegistrationBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("is_confirmed", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rental_object", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_admin.rentalobject")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_admin.telegramuser")),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="TelegramUserProfilePhotos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_id", models.CharField()),
                ("file_unique_id", models.CharField()),
                ("width", models.SmallIntegerField()),
                ("height", models.SmallIntegerField()),
                ("file_size", models.SmallIntegerField()),
                ("tg_user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_admin.telegramuser")),
            ],
        ),
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True, verbose_name="Время начала работы")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="Время окончания работы")),
            ],
            options={
                "verbose_name": "Рабочее время",
                "verbose_name_plural": "Рабочие времена",
                "ordering": ["day"],
                "unique_together": {("day", "start_time", "end_time")},
            },
        ),
        migrations.AddField(
            model_name="servicelocation",
            name="available_days",
            field=models.ManyToManyField(
                blank=True, related_name="service_locations", to="bot_admin.workday", verbose_name="Доступные дни недели"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalobject",
            index=models.Index(fields=["type_obj", "is_available"], name="bot_admin_r_type_ob_4de4d8_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationbook",
            index=models.Index(fields=["user", "rental_object"], name="bot_admin_r_user_id_cd3797_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationbook",
            index=models.Index(fields=["start_date", "end_date"], name="bot_admin_r_start_d_ae2e25_idx"),
        ),
        migrations.AddIndex(
            model_name="registrationbook",
            index=models.Index(fields=["start_datetime", "end_datetime"], name="bot_admin_r_start_d_6a9656_idx"),
        ),
    ]
