# Generated by Django 5.2.5 on 2025-08-06 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=32)),
                ("bio", models.CharField(max_length=70)),
                ("language_code", models.CharField(max_length=2)),
                ("is_premium", models.BooleanField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUserProfilePhotos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_id", models.CharField()),
                ("file_unique_id", models.CharField()),
                ("width", models.SmallIntegerField()),
                ("height", models.SmallIntegerField()),
                ("file_size", models.SmallIntegerField()),
                ("tg_user_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot_admin.telegramuser")),
            ],
        ),
    ]
